"""Error code definitions.

Format: DOMAIN_CATEGORY_DETAIL
"""

CIRCUIT_OPEN = "CIRCUIT_STATE_OPEN"
CIRCUIT_HALF_OPEN = "CIRCUIT_STATE_HALF_OPEN"
CIRCUIT_RECOVERED = "CIRCUIT_STATE_RECOVERED"

FALLBACK_PRIMARY_FAILED = "FALLBACK_PRIMARY_FAILED"
FALLBACK_SECONDARY_FAILED = "FALLBACK_SECONDARY_FAILED"
FALLBACK_SUCCESS = "FALLBACK_SUCCESS"

DOMAIN_VALIDATION_ERROR = "DOMAIN_VALIDATION_ERROR"
DOMAIN_RESOURCE_NOT_FOUND = "DOMAIN_RESOURCE_NOT_FOUND"
DOMAIN_TIMEOUT_ERROR = "DOMAIN_TIMEOUT_ERROR"
DOMAIN_INTERNAL_ERROR = "DOMAIN_INTERNAL_ERROR"

APPLICATION_SERVICE_ERROR = "APPLICATION_SERVICE_ERROR"
APPLICATION_ORCHESTRATION_ERROR = "APPLICATION_ORCHESTRATION_ERROR"

CLI_ARGUMENT_ERROR = "CLI_ARGUMENT_ERROR"
CLI_EXECUTION_ERROR = "CLI_EXECUTION_ERROR"

SUCCESS = "SUCCESS"
